// ─────────────────────────────────────────────────────────────────────────
//  소지품 그림 명단 — '보유 그림'의 단일 출처 (legacy emoji 목록에 해당).
//  · 서버(items.mjs): label 목록을 프롬프트에 넣어 Gemini가 '제일 비슷한 것'을 고르게.
//  · 프론트(Characters.tsx): 물건에 박제된 key로 `/assets/illust/items/<key>.webp` 경로.
//  · 파일 없어도 안전 — 폴백(fallback.webp). 명단·파일명·분류 = docs/에셋제작_소지품.md.
//  ⚠️ 정리는 '분류별'로 — 업로드 회차로 묶지 말 것. key=파일 stem, label=AI가 고를 한국어(겹치지 않게).
// ─────────────────────────────────────────────────────────────────────────

export const ITEM_ICONS = [

  // 1. 문서·기록
  { key: "documents", label: "서류" },
  { key: "letter", label: "서신" },
  { key: "scroll", label: "두루마리" },
  { key: "parchment", label: "양피지" },
  { key: "book", label: "서책" },
  { key: "bookmark", label: "책갈피" },
  { key: "ledger", label: "장부" },
  { key: "score", label: "악보" },
  { key: "sketch", label: "스케치" },
  { key: "map", label: "지도" },
  { key: "quill", label: "깃펜" },
  { key: "inkwell", label: "잉크병" },
  { key: "wanted", label: "현상수배서" },
  { key: "message-cylinder", label: "전령통" },
  { key: "paintbrush", label: "화필" },
  { key: "book-forbidden", label: "금서" },
  { key: "cipher", label: "암호문" },
  { key: "edict", label: "칙령" },
  { key: "journal", label: "일지" },
  { key: "scribe-kit", label: "필기구함" },
  { key: "tablet", label: "서판" },
  { key: "paperweight", label: "문진" },
  { key: "stamp", label: "도장" },
  { key: "certificate", label: "증서" },
  { key: "contract", label: "계약서" },
  { key: "envelope", label: "봉투" },
  { key: "family-tree", label: "가계도" },
  { key: "framed-painting", label: "액자 그림" },
  { key: "letter-bundle", label: "편지 묶음" },
  { key: "letter-opener", label: "편지칼" },
  { key: "notebook", label: "공책" },
  { key: "storybook", label: "이야기책" },
  { key: "star-chart", label: "성도" },
  { key: "canvas", label: "캔버스" },
  { key: "chalk", label: "분필" },
  { key: "book-stand", label: "서견대" },
  { key: "sealing-wax", label: "봉랍" },

  // 2. 장신구·기념품
  { key: "ring", label: "반지" },
  { key: "pendant", label: "펜던트" },
  { key: "necklace", label: "목걸이" },
  { key: "earring", label: "귀걸이" },
  { key: "bracelet", label: "팔찌" },
  { key: "brooch", label: "브로치" },
  { key: "hairpin", label: "머리 장식" },
  { key: "ribbon", label: "리본" },
  { key: "locket", label: "로켓" },
  { key: "tiara", label: "티아라" },
  { key: "medal", label: "메달" },
  { key: "badge", label: "휘장" },
  { key: "epaulet", label: "견장" },
  { key: "mirror", label: "손거울" },
  { key: "pocketwatch", label: "회중시계" },
  { key: "perfume", label: "향수병" },
  { key: "doll", label: "인형" },
  { key: "musicbox", label: "오르골" },
  { key: "dice", label: "주사위" },
  { key: "cards", label: "점술 카드" },
  { key: "chesspiece", label: "체스말" },
  { key: "coin", label: "동전" },
  { key: "crown", label: "왕관" },
  { key: "flower-crown", label: "화관" },
  { key: "gem", label: "보석" },
  { key: "jewel-box", label: "보석함" },
  { key: "miniature-portrait", label: "세밀 초상" },
  { key: "signet-ring", label: "인장 반지" },
  { key: "tassel", label: "술 장식" },
  { key: "plume", label: "깃털 장식" },
  { key: "amber", label: "호박석" },
  { key: "chain-of-office", label: "관직 사슬" },
  { key: "circlet", label: "서클릿" },
  { key: "glass-figurine", label: "유리 장식품" },
  { key: "hair-lock", label: "머리카락" },
  { key: "marbles", label: "구슬" },
  { key: "scepter", label: "왕홀" },
  { key: "spinning-top", label: "팽이" },
  { key: "toy-horse", label: "목마" },
  { key: "butterfly-specimen", label: "나비 표본" },
  { key: "cameo", label: "카메오" },
  { key: "compact-powder", label: "분첩" },
  { key: "cosmetic-brush", label: "화장솔" },
  { key: "cup-and-ball", label: "죽방울" },
  { key: "headband", label: "머리띠" },
  { key: "kite", label: "연" },
  { key: "lipstick", label: "립스틱" },
  { key: "marionette", label: "마리오네트" },
  { key: "model-ship", label: "모형 배" },
  { key: "perfumed-oil", label: "향유" },
  { key: "pinwheel", label: "바람개비" },
  { key: "pomander", label: "향구" },
  { key: "rattle", label: "딸랑이" },
  { key: "sachet", label: "향낭" },
  { key: "snuffbox", label: "코담배갑" },
  { key: "tear-bottle", label: "눈물병" },
  { key: "teddy-bear", label: "곰 인형" },
  { key: "toy-soldier", label: "장난감 병정" },
  { key: "trophy", label: "트로피" },
  { key: "wood-carving", label: "목각" },
  { key: "amethyst", label: "자수정" },
  { key: "emerald", label: "에메랄드" },
  { key: "ruby", label: "루비" },
  { key: "sapphire", label: "사파이어" },
  { key: "pearl", label: "진주" },
  { key: "gift-box", label: "선물 상자" },
  { key: "ball", label: "공" },
  { key: "tambourine", label: "탬버린" },
  { key: "fiddle", label: "바이올린" },

  // 3. 생활·도구
  { key: "candle", label: "양초" },
  { key: "lantern", label: "등불" },
  { key: "kettle", label: "주전자" },
  { key: "goblet", label: "고블릿" },
  { key: "basket", label: "바구니" },
  { key: "broom", label: "빗자루" },
  { key: "hammer", label: "망치" },
  { key: "soap", label: "비누" },
  { key: "bell", label: "종" },
  { key: "flute", label: "플루트" },
  { key: "lute", label: "류트" },
  { key: "oilflask", label: "기름병" },
  { key: "comb", label: "빗" },
  { key: "fan", label: "부채" },
  { key: "pipe", label: "담뱃대" },
  { key: "padlock", label: "자물쇠" },
  { key: "fishingrod", label: "낚싯대" },
  { key: "trowel", label: "모종삽" },
  { key: "needle", label: "바늘과 실" },
  { key: "rope", label: "끈" },
  { key: "flint", label: "부싯돌" },
  { key: "hourglass", label: "모래시계" },
  { key: "compass", label: "나침반" },
  { key: "spyglass", label: "망원경" },
  { key: "scale", label: "저울" },
  { key: "cord", label: "노끈" },
  { key: "birdcage", label: "새장" },
  { key: "embroidery-hoop", label: "자수틀" },
  { key: "harp", label: "하프" },
  { key: "ocarina", label: "오카리나" },
  { key: "thimble", label: "골무" },
  { key: "abacus", label: "주판" },
  { key: "astrolabe", label: "아스트롤라베" },
  { key: "backpack-common", label: "평민 배낭" },
  { key: "backpack-nobles", label: "귀족 배낭" },
  { key: "butterfly-net", label: "포충망" },
  { key: "candle-stub", label: "양초 토막" },
  { key: "cane", label: "단장" },
  { key: "ceramic-pitcher", label: "도자기 물병" },
  { key: "clay-pot", label: "토기" },
  { key: "drum", label: "북" },
  { key: "dye", label: "염료" },
  { key: "glasses", label: "안경" },
  { key: "handbag", label: "손가방" },
  { key: "magnifier", label: "돋보기" },
  { key: "monocle", label: "단안경" },
  { key: "palette", label: "팔레트" },
  { key: "parasol", label: "양산" },
  { key: "pouch", label: "주머니" },
  { key: "shuttle", label: "베틀북" },
  { key: "spool", label: "실패" },
  { key: "whistle", label: "호루라기" },
  { key: "wind-chime", label: "풍경" },
  { key: "anvil", label: "모루" },
  { key: "bellows", label: "풀무" },
  { key: "chisel", label: "끌" },
  { key: "mallet", label: "나무망치" },
  { key: "saw", label: "톱" },
  { key: "plane", label: "대패" },
  { key: "tongs", label: "집게" },
  { key: "pickaxe", label: "곡괭이" },
  { key: "shovel", label: "삽" },
  { key: "hoe", label: "괭이" },
  { key: "sickle", label: "낫" },
  { key: "scissors", label: "가위" },
  { key: "nails", label: "못" },
  { key: "crucible", label: "도가니" },
  { key: "alembic", label: "증류기" },
  { key: "mortar", label: "절구" },
  { key: "cauldron", label: "가마솥" },
  { key: "duster", label: "먼지떨이" },
  { key: "iron", label: "다리미" },
  { key: "ingot", label: "주괴" },
  { key: "bowl", label: "그릇" },
  { key: "plate", label: "접시" },
  { key: "tray", label: "쟁반" },
  { key: "mug", label: "머그" },
  { key: "spoon", label: "숟가락" },
  { key: "fork", label: "포크" },
  { key: "jar", label: "항아리" },
  { key: "glass-bottle", label: "유리병" },
  { key: "flask", label: "플라스크" },
  { key: "waterskin", label: "물주머니" },
  { key: "teapot", label: "찻주전자" },
  { key: "barrel", label: "통" },
  { key: "bucket", label: "양동이" },
  { key: "chest", label: "나무 상자" },
  { key: "vase", label: "꽃병" },
  { key: "specimen-jar", label: "표본병" },
  { key: "rolling-pin", label: "밀대" },
  { key: "candelabra", label: "촛대" },
  { key: "torch", label: "횃불" },
  { key: "globe", label: "지구본" },
  { key: "sundial", label: "해시계" },
  { key: "drawing-compass", label: "제도용 컴퍼스" },
  { key: "ruler", label: "자" },
  { key: "towel", label: "수건" },
  { key: "washboard", label: "빨래판" },
  { key: "washbasin", label: "대야" },
  { key: "watering-can", label: "물뿌리개" },
  { key: "seeds", label: "씨앗" },
  { key: "lockpick", label: "자물쇠따개" },
  { key: "trap", label: "덫" },
  { key: "grappling-hook", label: "갈고리" },
  { key: "fishing-net", label: "낚시 그물" },
  { key: "bait", label: "미끼" },
  { key: "umbrella", label: "우산" },
  { key: "crutch", label: "목발" },
  { key: "pillow", label: "베개" },
  { key: "blanket", label: "담요" },
  { key: "scarecrow", label: "허수아비" },
  { key: "chess-board", label: "체스판" },

  // 4. 의복·천
  { key: "cloth", label: "천 조각" },
  { key: "handkerchief", label: "손수건" },
  { key: "glove-leather", label: "가죽 장갑" },
  { key: "glove-silk", label: "실크 장갑" },
  { key: "boots-leather", label: "가죽 장화" },
  { key: "cloak", label: "망토" },
  { key: "eyepatch", label: "안대" },
  { key: "mask", label: "가면" },
  { key: "hat", label: "모자" },
  { key: "scarf", label: "스카프" },
  { key: "belt-leather", label: "가죽 허리띠" },
  { key: "button", label: "단추" },
  { key: "apron", label: "앞치마" },
  { key: "hood", label: "두건" },
  { key: "veil", label: "베일" },
  { key: "cloak-clasp", label: "망토 걸쇠" },
  { key: "baby-shoes", label: "아기 신발" },
  { key: "belt-silk", label: "실크 허리띠" },
  { key: "blouse", label: "블라우스" },
  { key: "boots-fur", label: "털 장화" },
  { key: "boots-riding", label: "승마 장화" },
  { key: "breeches", label: "브리치스" },
  { key: "buckle", label: "버클" },
  { key: "cape", label: "케이프" },
  { key: "chemise", label: "슈미즈" },
  { key: "clogs", label: "나막신" },
  { key: "coat", label: "코트" },
  { key: "collar", label: "옷깃" },
  { key: "corset", label: "코르셋" },
  { key: "cravat", label: "크라바트" },
  { key: "dancing-shoes", label: "무도화" },
  { key: "doublet", label: "더블릿" },
  { key: "dress-common", label: "평민 드레스" },
  { key: "dress-nobles", label: "귀족 드레스" },
  { key: "dressing-gown", label: "실내복" },
  { key: "earmuffs", label: "귀마개" },
  { key: "fabric-bolt", label: "옷감" },
  { key: "fur", label: "모피" },
  { key: "fur-stole", label: "모피 숄" },
  { key: "garter-common", label: "평민 가터" },
  { key: "garter-nobles", label: "귀족 가터" },
  { key: "hat-cap", label: "캡모자" },
  { key: "hat-plumed", label: "깃털 모자" },
  { key: "hat-straw", label: "밀짚모자" },
  { key: "kerchief", label: "머릿수건" },
  { key: "lace", label: "레이스" },
  { key: "leather", label: "가죽" },
  { key: "mittens", label: "벙어리장갑" },
  { key: "mourning-dress", label: "상복" },
  { key: "muff", label: "토시" },
  { key: "nightcap", label: "나이트캡" },
  { key: "nightgown", label: "잠옷" },
  { key: "petticoat", label: "페티코트" },
  { key: "rag", label: "헝겊" },
  { key: "sampler", label: "자수 견본" },
  { key: "sash", label: "장식 띠" },
  { key: "shawl", label: "숄" },
  { key: "shirt", label: "셔츠" },
  { key: "shoes", label: "신발" },
  { key: "skirt", label: "치마" },
  { key: "slippers", label: "슬리퍼" },
  { key: "socks-common", label: "평민 양말" },
  { key: "socks-nobles", label: "귀족 양말" },
  { key: "stockings", label: "스타킹" },
  { key: "trousers", label: "바지" },
  { key: "tunic", label: "튜닉" },
  { key: "uniform", label: "제복" },
  { key: "vest", label: "조끼" },
  { key: "wig", label: "가발" },
  { key: "wool", label: "양털" },
  { key: "yarn", label: "실타래" },

  // 5. 무기·군용품
  { key: "dagger", label: "단검" },
  { key: "sword", label: "검" },
  { key: "bow", label: "활" },
  { key: "arrow", label: "화살촉" },
  { key: "lance", label: "창" },
  { key: "axe", label: "도끼" },
  { key: "mace", label: "철퇴" },
  { key: "whip", label: "채찍" },
  { key: "shield", label: "방패" },
  { key: "armor", label: "갑주 조각" },
  { key: "helmet", label: "투구" },
  { key: "gauntlet", label: "건틀릿" },
  { key: "whetstone", label: "숫돌" },
  { key: "scabbard", label: "칼집" },
  { key: "quiver", label: "화살통" },
  { key: "horn", label: "나팔" },
  { key: "banner", label: "깃발" },
  { key: "stirrup", label: "등자" },
  { key: "sleeping-bag", label: "야영 침구" },
  { key: "bandage", label: "붕대" },
  { key: "tome", label: "마도서" },
  { key: "staff", label: "지팡이" },
  { key: "insignia", label: "계급장" },
  { key: "baton", label: "지휘봉" },
  { key: "spurs", label: "박차" },
  { key: "wooden-sword", label: "목검" },
  { key: "crossbow", label: "석궁" },
  { key: "target", label: "과녁" },
  { key: "bracer", label: "팔보호대" },
  { key: "tent", label: "천막" },
  { key: "saddle", label: "안장" },
  { key: "horseshoe", label: "편자" },
  { key: "riding-crop", label: "승마 채찍" },
  { key: "horse-brush", label: "말빗" },
  { key: "falcon-hood", label: "매 두건" },
  { key: "collar-pet", label: "반려동물 목줄" },

  // 6. 종교·주술물
  { key: "statue-goddess", label: "여신상" },
  { key: "rosary", label: "묵주" },
  { key: "prayerbook", label: "기도서" },
  { key: "charm", label: "부적" },
  { key: "chalice", label: "성배" },
  { key: "censer", label: "향로" },
  { key: "orb", label: "수정구" },
  { key: "reliquary", label: "성유물함" },
  { key: "runestone", label: "룬석" },
  { key: "robe-clerical", label: "성직자 로브" },
  { key: "holy-water", label: "성수" },
  { key: "incense", label: "향" },
  { key: "votive-candle", label: "봉헌 양초" },
  { key: "wand", label: "완드" },

  // 7. 증표·불명물
  { key: "key", label: "열쇠" },
  { key: "seal", label: "인장" },
  { key: "shard", label: "파편" },
  { key: "bundle", label: "수상한 꾸러미" },
  { key: "sack", label: "자루" },
  { key: "shackles", label: "족쇄" },
  { key: "skull", label: "두개골" },
  { key: "crystal", label: "검은 결정" },
  { key: "puzzlebox", label: "수수께끼 상자" },
  { key: "powder-dirty", label: "수상한 가루" },
  { key: "broken-blade", label: "부러진 칼날" },
  { key: "broken-glass", label: "깨진 유리" },
  { key: "broken-wood", label: "부서진 나무" },
  { key: "coin-half", label: "반쪽 동전" },
  { key: "crest-plaque", label: "문장패" },
  { key: "keyring", label: "열쇠고리" },
  { key: "rusty-chain", label: "녹슨 사슬" },
  { key: "rusty-nail", label: "녹슨 못" },
  { key: "shard-pottery", label: "도기 파편" },
  { key: "coin-pouch", label: "돈주머니" },
  { key: "poison-vial", label: "독병" },

  // 8. 약초·꽃
  { key: "herb", label: "약초" },
  { key: "tea-leaves", label: "찻잎" },
  { key: "vial", label: "약병" },
  { key: "flower-camellia", label: "동백" },
  { key: "flower-carnation", label: "카네이션" },
  { key: "flower-chrysanthemum", label: "국화" },
  { key: "flower-daisy", label: "데이지" },
  { key: "flower-iris", label: "붓꽃" },
  { key: "flower-lavender", label: "라벤더" },
  { key: "flower-lily", label: "백합" },
  { key: "flower-rose", label: "장미" },
  { key: "flower-sunflower", label: "해바라기" },
  { key: "flower-tulip", label: "튤립" },
  { key: "pressed-flower", label: "압화" },
  { key: "bouquet", label: "꽃다발" },
  { key: "bouquet-dried", label: "마른 꽃다발" },
  { key: "flower-anemone", label: "아네모네" },
  { key: "flower-daffodil", label: "수선화" },
  { key: "flower-forget-me-not", label: "물망초" },
  { key: "flower-lily-of-the-valley", label: "은방울꽃" },
  { key: "flower-marigold", label: "금잔화" },
  { key: "flower-peony", label: "작약" },
  { key: "flower-poppy", label: "양귀비" },
  { key: "flower-snowdrop", label: "스노드롭" },
  { key: "flower-violet", label: "제비꽃" },
  { key: "wreath", label: "화환" },
  { key: "salve", label: "연고" },

  // 9. 자연물
  { key: "leaf", label: "나뭇잎" },
  { key: "moss", label: "이끼" },
  { key: "twig", label: "잔가지" },
  { key: "bark", label: "나무껍질" },
  { key: "vine", label: "덩굴" },
  { key: "petal", label: "꽃잎" },
  { key: "pinecone", label: "솔방울" },
  { key: "acorn", label: "도토리" },
  { key: "seashell", label: "조개껍데기" },
  { key: "feather", label: "깃털" },
  { key: "clover", label: "클로버" },
  { key: "pebble", label: "조약돌" },
  { key: "straw", label: "짚" },
  { key: "antler", label: "뿔" },
  { key: "tuft-of-fur", label: "털 뭉치" },
  { key: "wheat-sheaf", label: "밀짚단" },

  // 10. 음식·식재료
  // — 조리·가공식
  { key: "food-bacon", label: "베이컨" },
  { key: "food-beer", label: "맥주" },
  { key: "food-biscuit", label: "비스킷" },
  { key: "food-bread", label: "빵" },
  { key: "food-butter", label: "버터" },
  { key: "food-cake", label: "케이크" },
  { key: "food-candy", label: "사탕" },
  { key: "food-cheese", label: "치즈" },
  { key: "food-chicken", label: "닭고기" },
  { key: "food-chocolate", label: "초콜릿" },
  { key: "food-cookie", label: "쿠키" },
  { key: "food-cream", label: "크림" },
  { key: "food-dessert", label: "디저트" },
  { key: "food-donut", label: "도넛" },
  { key: "food-dried-fruit", label: "말린 과일" },
  { key: "food-egg", label: "달걀" },
  { key: "food-fish-dish", label: "생선 요리" },
  { key: "food-fish", label: "생선" },
  { key: "food-ham", label: "햄" },
  { key: "food-honey", label: "꿀" },
  { key: "food-icecream", label: "아이스크림" },
  { key: "food-jam", label: "잼" },
  { key: "food-jelly", label: "젤리" },
  { key: "food-jerky", label: "육포" },
  { key: "food-juice", label: "주스" },
  { key: "food-liquor", label: "술" },
  { key: "food-macaroon", label: "마카롱" },
  { key: "food-meat-dish", label: "고기 요리" },
  { key: "food-milk", label: "우유" },
  { key: "food-noodle", label: "국수" },
  { key: "food-nuts", label: "견과" },
  { key: "food-pancake", label: "팬케이크" },
  { key: "food-pasta", label: "파스타" },
  { key: "food-pie", label: "파이" },
  { key: "food-porridge", label: "죽" },
  { key: "food-pudding", label: "푸딩" },
  { key: "food-roast", label: "구이" },
  { key: "food-salad", label: "샐러드" },
  { key: "food-sandwich", label: "샌드위치" },
  { key: "food-sausage", label: "소시지" },
  { key: "food-seafood", label: "해산물" },
  { key: "food-skewer", label: "꼬치" },
  { key: "food-soup", label: "수프" },
  { key: "food-spice", label: "향신료" },
  { key: "food-steak", label: "스테이크" },
  { key: "food-stew", label: "스튜" },
  { key: "food-tart", label: "타르트" },
  { key: "food-tea", label: "차" },
  { key: "food-vegetable-dish", label: "채소 요리" },
  { key: "food-water", label: "물" },
  { key: "food-wine", label: "와인" },
  { key: "food-yogurt", label: "요거트" },
  { key: "food-candy-tin", label: "사탕 통" },
  // — 과일
  { key: "fruit-apple", label: "사과" },
  { key: "fruit-berry", label: "베리" },
  { key: "fruit-cherry", label: "체리" },
  { key: "fruit-fig", label: "무화과" },
  { key: "fruit-grapes", label: "포도" },
  { key: "fruit-lemon", label: "레몬" },
  { key: "fruit-melon", label: "멜론" },
  { key: "fruit-orange", label: "오렌지" },
  { key: "fruit-peach", label: "복숭아" },
  { key: "fruit-pear", label: "배" },
  { key: "fruit-pomegranate", label: "석류" },
  // — 채소
  { key: "veg-cabbage", label: "양배추" },
  { key: "veg-carrot", label: "당근" },
  { key: "veg-corn", label: "옥수수" },
  { key: "veg-garlic", label: "마늘" },
  { key: "veg-mushroom", label: "버섯" },
  { key: "veg-onion", label: "양파" },
  { key: "veg-potato", label: "감자" },
  { key: "veg-pumpkin", label: "호박" },
  { key: "veg-turnip", label: "순무" },

  // 11. 마물 소재
  { key: "beasts-blood", label: "마물 피" },
  { key: "beasts-bone", label: "마물 뼈" },
  { key: "beasts-claw", label: "마물 발톱" },
  { key: "beasts-fang", label: "마물 송곳니" },
  { key: "beasts-hide", label: "마물 가죽" },
  { key: "beasts-horn", label: "마물 뿔" },
  { key: "beasts-scale", label: "마물 비늘" },

];

// label → key 빠른 조회.

export const ICON_BY_LABEL = new Map(ITEM_ICONS.map((i) => [i.label, i.key]));

// 유효한 key 집합.

export const ICON_KEYS = new Set(ITEM_ICONS.map((i) => i.key));
