// ⚠️ 자동 생성 파일 — 직접 수정하지 마세요.
// worldview/풍화설월_고유명사_사전.md 가 바뀌면 'npm run bake' 로 다시 만듭니다.
// { 정발 표기(한글) → 원어(영문) } — 영문명 자동 매칭용.
export const nameDict: Record<string, string> = {
  "벨레스 아이스너": "Byleth Eisner",
  "제랄트 로이스 아이스너": "Jeralt Reus Eisner",
  "시트리 아이스너": "Sitri Eisner",
  "디미트리 알렉산드르 블레다드": "Dimitri Alexandre Blaiddyd",
  "두두 몰리나로": "Dedue Molinaro",
  "펠릭스 유고 프랄다리우스": "Felix Hugo Fraldarius",
  "메르세데스 폰 마르트리츠": "Mercedes von Martritz",
  "애쉬 듀란": "Ashe Ubert",
  "아네트 팡틴 도미닉": "Annette Fantine Dominic",
  "실뱅 조제 고티에": "Sylvain Jose Gautier",
  "잉그리트 브란들 갈라테아": "Ingrid Brandl Galatea",
  "람베르 에지트 블레다드": "Lambert Egitte Blaiddyd",
  "패트리샤": "Patricia",
  "루퍼스 티어리 블레다드": "Rufus Tieri Blaiddyd",
  "코넬리아 아르님": "Cornelia Arnim",
  "로드릭 아시르 프랄다리우스": "Rodrigue Achille Fraldarius",
  "그렌 고반 프랄다리우스": "Glenn Fraldarius",
  "마티아스 라울 고티에": "Matthias Raoul Gautier",
  "구스타브 에디 도미닉": "Gustave Eddie Dominic",
  "카산드라 루벤스 카론": "Cassandra Rubens Charon",
  "로나토 질다 가스파르": "Lonato Gildas Gaspard",
  "그웬달 로쉬": "Gwendal Roche",
  "마이클란 안슈츠 고티에": "Miklan Anschutz Gautier",
  "클로드 폰 리건": "Claude von Riegan",
  "로렌츠 헤르만 글로스터": "Lorenz Hellman Gloucester",
  "힐다 발렌틴 고네릴": "Hilda Valentine Goneril",
  "라파엘 키르스텐": "Raphael Kirsten",
  "리시테아 폰 코델리아": "Lysithea von Cordelia",
  "이그나츠 빅터": "Ignatz Victor",
  "마리안 폰 에드먼드": "Marianne von Edmund",
  "레오니 피넬리": "Leonie Pinelli",
  "오즈왈드 폰 리건": "Oswald von Riegan",
  "고드프루아 폰 리건": "Godfrey von Riegan",
  "주디트 폰 다프넬": "Judith von Daphnel",
  "홀스트 지기스발트 고네릴": "Holst Sigiswald Goneril",
  "엘빈 프리츠 글로스터": "Erwin Fritz Gloucester",
  "아케론 레테 플레게톤": "Acheron Lethe Phlegethon",
  "에델가르트 폰 흐레스벨그": "Edelgard von Hresvelg",
  "휴베르트 폰 베스트라": "Hubert von Vestra",
  "도로테아 아르놀트": "Dorothea Arnault",
  "페르디난트 폰 에기르": "Ferdinand von Aegir",
  "베르나데타 폰 발리": "Bernadetta von Varley",
  "카스파르 폰 베르그리즈": "Caspar von Bergliez",
  "페트라 맥네어리": "Petra Macneary",
  "린하르트 폰 헤브링": "Linhardt von Hevring",
  "모니카 폰 옥스": "Monica von Ochs",
  "이오니아스 9세": "Ionius IX",
  "빌헬름 파울 흐레스벨그": "Wilhelm Paul Hresvelg",
  "안젤마 폰 아룬델": "Anselma von Arundel",
  "폴크하르트 폰 아룬델": "Volkhard von Arundel",
  "예리차 폰 프륨": "Jeritza von Hrym",
  "라디슬라바": "Ladislava",
  "메토제이": "Metodey",
  "루트비히 폰 에기르": "Ludwig von Aegir",
  "레오폴트 폰 베르그리즈": "Leopold von Bergliez",
  "발데마르 폰 헤브링": "Waldemar von Hevring",
  "그레고어 폰 발리": "Grégoire von Varley",
  "란돌프 폰 베르그리즈": "Randolph von Bergliez",
  "플레체 폰 베르그리즈": "Fleche von Bergliez",
  "소티스": "Sothis",
  "레아": "Rhea",
  "세테스": "Seteth",
  "흐렌": "Flayn",
  "카트린": "Catherine",
  "알로이스 랑게르트": "Alois Rangeld",
  "길베르트 프로스닐라프": "Gilbert Pronislav",
  "샤미아 네브란트": "Shamir Nevrand",
  "시릴": "Cyril",
  "한네만 폰 에사": "Hanneman von Essar",
  "마누엘라 카자그란다": "Manuela Casagranda",
  "토마슈": "Tomas",
  "안나": "Anna",
  "알파드 달만": "Aelfric Dahlman",
  "율리스 르클레르": "Yuri Leclerc",
  "발타자르 폰 아달브레히트": "Balthus von Albrecht",
  "콘스탄체 폰 누벨": "Constance Von Nuvelle",
  "하피": "Hapi",
  "나데르": "Nader",
  "샤하드": "Shahid",
  "칼리드": "Khalid",
  "티아나 폰 리건": "Tiana von Riegan",
  "탈레스": "Thales",
  "클레오불루스": "Cleobulus",
  "크로니예": "Kronya",
  "솔론": "Solon",
  "뮈손": "Myson",
  "오디세": "Odesse",
  "비아스": "Bias",
  "아낙시만드로스": "Anaximander",
  "돌로폴노스": "Dolofolnos",
  "세이로스": "Seiros",
  "키홀": "Cichol",
  "세스린": "Cethleann",
  "인데히": "Indech",
  "마쿠일": "Macuil",
  "네메시스": "Nemesis",
  "블레다드": "Blaiddyd",
  "리건": "Riegan",
  "라민": "Lamine",
  "고네릴": "Goneril",
  "다프넬": "Daphnel",
  "도미닉": "Dominic",
  "고티에": "Gautier",
  "프랄다리우스": "Fraldarius",
  "글로스터": "Gloucester",
  "카론": "Charon",
  "코스타스": "Kostas",
  "바야르노 다비노": "Pallardó Davino",
  "포드라": "Fódlan",
  "팔미라": "Almyra",
  "알비네": "Albinea",
  "모르피스": "Morfis",
  "다그다": "Dagda",
  "브리기트": "Brigid",
  "스렝": "Sreng",
  "더스커": "Duscur",
  "오그마 산맥": "Oghma Mountains",
  "쿠팔라": "Kupala",
  "샴발라": "Shambhala",
  "퍼거스 신성 왕국": "Holy Kingdom of Faerghus",
  "페르디아": "Fhirdiad",
  "블레다드 왕가": "Blaiddyd",
  "프랄다리우스 공작가": "Fraldarius",
  "고티에 변경백가": "Gautier",
  "이반 공작가": "Ivaldi",
  "카론 백작가": "Charon",
  "갈라테아 백작가": "Galatea",
  "도미닉 남작가": "Dominic",
  "로베 백작가": "Rowe",
  "클레이만 자작가": "Kleiman",
  "에레보스 후작가": "Erebus",
  "듀발 백작가": "Duval",
  "프라이데리 남작가": "Freidery",
  "벨리나스 자작가": "Belinas",
  "블레나스 자작가": "Blenas",
  "기디온 자작가": "Gideon",
  "엘리듀어 자작가": "Elidure",
  "마테우스 자작가": "Matheus",
  "게라인트 백작가": "Geraint",
  "이니드 자작가": "Enid",
  "아리안로드": "Arianrhod",
  "연옥의 계곡 아릴": "Aillell, the Valley of Torment",
  "탈틴 평원": "Tailtean Plains",
  "레스터 제후 동맹": "Leicester Alliance",
  "디아도라": "Deirdre",
  "리건 공작가": "Riegan",
  "고네릴 공작가": "Goneril",
  "코델리아 백작가": "Cordelia",
  "글로스터 백작가": "Gloucester",
  "에드먼드 변경백가": "Edmund",
  "다프넬 후작가": "Daphnel",
  "플레게톤 자작가": "Phlegethon",
  "시워드 자작가": "Seward",
  "올버니 자작가": "Albany",
  "버건디 자작가": "Burgundy",
  "아달브레히트 남작가": "Adalbrecht",
  "뮐러 남작가": "Müller",
  "넬슨 자작가": "Nelson",
  "미르딘 대교": "Great Bridge of Myrddin",
  "포드라의 목": "Fódlan's Throat",
  "포드라의 목걸이": "Fódlan's Locket",
  "아드라스테아 제국": "Adrestian Empire",
  "앙바르": "Enbarr",
  "흐레스벨그 황가": "Hresvelg",
  "에기르 공작가": "Aegir",
  "베스트라 후작가": "Vestra",
  "헤브링 백작가": "Hevring",
  "베르그리즈 백작가": "Bergliez",
  "발리 백작가": "Varley",
  "겔즈 공작가": "Gerth",
  "아룬델 공작가": "Arundel",
  "프륨 자작가": "Hrym",
  "누벨 자작가": "Nuvelle",
  "옥스 남작가": "Ochs",
  "마르트리츠 남작가": "Martritz",
  "바르텔스 남작가": "Bartels",
  "페냐 자작가": "Fenja",
  "메냐 자작가": "Menja",
  "길링 남작가": "Gilling",
  "에사 자작가": "Essar",
  "로킨 자작가": "Lochin",
  "마르킨 남작가": "Marquin",
  "바르나바쉬 남작가": "Barnabas",
  "그론다즈 평원": "Gronder Field",
  "메리세우스 요새": "Fort Merceus",
  "잿빛 악마": "Ashen Demon",
  "더스커의 비극": "Tragedy of Duscur",
  "7귀족의 변": "Insurrection of the Seven"
};
